data = [
    {'name': 'Instagram', 'follower_count': 684, 'description': 'Social media platform', 'country': 'United States'},
    {'name': 'Cristiano Ronaldo', 'follower_count': 647, 'description': 'Footballer', 'country': 'Portugal'},
    {'name': 'Ariana Grande', 'follower_count': 376, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Dwayne Johnson', 'follower_count': 394, 'description': 'Actor and professional wrestler', 'country': 'United States'},
    {'name': 'Selena Gomez', 'follower_count': 423, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Kylie Jenner', 'follower_count': 395, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Kim Kardashian', 'follower_count': 359, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Lionel Messi', 'follower_count': 504, 'description': 'Footballer', 'country': 'Argentina'},
    {'name': 'Beyoncé', 'follower_count': 313, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Neymar', 'follower_count': 227, 'description': 'Footballer', 'country': 'Brazil'},
    {'name': 'National Geographic', 'follower_count': 280, 'description': 'Magazine', 'country': 'United States'},
    {'name': 'Justin Bieber', 'follower_count': 295, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Taylor Swift', 'follower_count': 283, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kendall Jenner', 'follower_count': 290, 'description': 'Reality TV personality and model', 'country': 'United States'},
    {'name': 'Jennifer Lopez', 'follower_count': 249, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Nicki Minaj', 'follower_count': 227, 'description': 'Musician', 'country': 'Trinidad and Tobago'},
    {'name': 'Nike', 'follower_count': 302, 'description': 'Sportswear multinational', 'country': 'United States'},
    {'name': 'Khloé Kardashian', 'follower_count': 305, 'description': 'Reality TV personality and businesswoman', 'country': 'United States'},
    {'name': 'Miley Cyrus', 'follower_count': 213, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Katy Perry', 'follower_count': 205, 'description': 'Musician', 'country': 'United States'},
    {'name': 'Kourtney Kardashian', 'follower_count': 220, 'description': 'Reality TV personality', 'country': 'United States'},
    {'name': 'Kevin Hart', 'follower_count': 177, 'description': 'Comedian and actor', 'country': 'United States'},
    {'name': 'Ellen DeGeneres', 'follower_count': 137, 'description': 'Comedian', 'country': 'United States'},
    {'name': 'Real Madrid CF', 'follower_count': 170, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'FC Barcelona', 'follower_count': 133, 'description': 'Football club', 'country': 'Spain'},
    {'name': 'Rihanna', 'follower_count': 150, 'description': 'Musician and businesswoman', 'country': 'Barbados'},
    {'name': 'Demi Lovato', 'follower_count': 154, 'description': 'Musician and actress', 'country': 'United States'},
    {'name': 'Zendaya', 'follower_count': 180, 'description': 'Actress and musician', 'country': 'United States'},
    {'name': 'Shakira', 'follower_count': 90.8, 'description': 'Musician', 'country': 'Colombia'},
    {'name': 'Drake', 'follower_count': 143, 'description': 'Musician', 'country': 'Canada'},
    {'name': 'Chris Brown', 'follower_count': 144, 'description': 'Musician', 'country': 'United States'},
    {'name': 'LeBron James', 'follower_count': 159, 'description': 'Basketball player', 'country': 'United States'},
    {'name': 'Vin Diesel', 'follower_count': 103, 'description': 'Actor', 'country': 'United States'},
    {'name': 'Cardi B', 'follower_count': 164, 'description': 'Musician', 'country': 'United States'},
    {'name': 'David Beckham', 'follower_count': 88.3, 'description': 'Footballer', 'country': 'United Kingdom'},
    {'name': 'Billie Eilish', 'follower_count': 121, 'description': 'Musician', 'country': 'United States'},
    {'name': 'UEFA Champions League', 'follower_count': 118, 'description': 'Club football competition', 'country': 'Europe'},
    {'name': 'NASA', 'follower_count': 96.9, 'description': 'Space agency', 'country': 'United States'},
    {'name': 'Virat Kohli', 'follower_count': 270, 'description': 'Cricketer', 'country': 'India'},
    {'name': 'Priyanka Chopra Jonas', 'follower_count': 92.6, 'description': 'Actress and musician', 'country': 'India'},
    {'name': 'NBA', 'follower_count': 89.2, 'description': 'Club Basketball Competition', 'country': 'United States'}
]
